### ISSUE TITLE
Lmfao already broken

### ISSUE THREAD

**Issue by crosssitescript** [Inplex-sys/telnet-bruter#1]
Broken asf 
./combos.c: In function ‘combos_init’:
./combos.c:52:33: error: expected ‘;’ before ‘combo_add’
   52 |     combo_add("admin", "123456")
      |                                 ^
      |                                 ;
   53 |     combo_add("hikvision", "hikvision");
      |     ~~~~~~~~~
Fixed it by adding ; to that line but how tf you gonna brute when it doesn't ask for file to brute I also did run with 5 threads or lower or higher and it didn't even scan it didn't even brute either

**Comment by Inplex-sys** [comment]
yes, my bad, fixed

**Comment by crosssitescript** [comment]
You didnt fix :'( it still doesn't even scan or brute anything

**Comment by crosssitescript** [comment]
![Screenshot_20220924_155122](https://user-images.githubusercontent.com/60415329/192129095-35c59846-cc8b-4c33-9144-ed96587ba6ff.jpg)
