### ISSUE TITLE
Script doesnt brute or scan?

### ISSUE THREAD

**Issue by crosssitescript** [Inplex-sys/telnet-bruter#2]
![Screenshot_20220924_155122](https://user-images.githubusercontent.com/60415329/192129621-f227bd92-8c8a-4871-91e9-70dbe328a4e7.jpg)

**Comment by Inplex-sys** [comment]
Put your file in stdin `cat fucker.txt | ./telnet-bruter 5`

**Comment by crosssitescript** [comment]
Thanks

**Comment by crosssitescript** [comment]
Next time when you post scripts can you show full tutorial on how to use it like all the commands

**Comment by crosssitescript** [comment]
Also found out threads don't even do nothing so I just left it at 1 cuz putting it up more the threads didn't make it faster or anything

**Comment by Inplex-sys** [comment]
Use just one thread it's better
